
/* 임시데이터 */
const TEMP_API_LIST_DATA = {
    see: {
        "성남시" : {
            totalCount : 1,
            perPage : 12, 
            categories: ['전체', '박물관', '도서관', '지역명소', '공원'],
            items : [
                {
                    id: 1,
                    title: '수원 화성',
                    category: '지역명소',
                    description: '조선 정조가 축성한 세계문화유산',
                    image: 'https://picsum.photos/id/1011/800/600',
                    rating: 4.5,
                    reviews: 120,
                    liked : true,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-01 12:00:00',
                    update_at: '2024-05-01 12:00:00',
                    detail: {},
                },
                {
                    id: 2,
                    title: '화성행궁',
                    category: '지역명소',
                    description: '정조가 머물던 임시 궁궐',
                    image: 'https://picsum.photos/id/1015/800/600',
                    rating: 3.5,
                    reviews: 98,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-01 12:00:00',
                    update_at: '2024-05-01 12:00:00',
                    detail: {},
                },
                {
                    id: 3,
                    title: '광교호수공원',
                    category: '공원',
                    description: '도심 속 힐링 호수 공원',
                    image: 'https://picsum.photos/id/1016/800/600',
                    rating: 3.2,
                    reviews: 208,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
                {
                    id: 4,
                    title: '만석공원',
                    category: '공원',
                    description: '조용한 힐링 공원',
                    image: 'https://picsum.photos/id/1020/800/600',
                    rating: 3.0,
                    reviews: 150,
                    location: '수원시 장안구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-04-29 00:00:00',
                    update_at: '2024-04-29 00:00:00',
                    detail: {},
                },
                {
                    id: 5,
                    title: '서호공원',
                    category: '공원',
                    description: '노을이 아름다운 호수 공원',
                    image: 'https://picsum.photos/id/1024/800/600',
                    rating: 1.6,
                    reviews: 80,
                    location: '수원시 권선구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-04-25 00:00:00',
                    update_at: '2024-04-25 00:00:00',
                    detail: {},
                },
                {
                    id: 6,
                    title: '수원박물관',
                    category: '박물관',
                    description: '수원의 역사와 문화를 한눈에',
                    image: 'https://picsum.photos/id/1027/800/600',
                    rating: 1.2,
                    reviews: 60,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '박물관',
                    create_at: '2024-05-04 00:00:00',
                    update_at: '2024-05-04 00:00:00',
                    detail: {},
                },
                {
                    id: 7,
                    title: '삼성이노베이션뮤지엄',
                    category: '박물관',
                    description: '삼성의 기술 발전을 볼 수 있는 공간',
                    image: 'https://picsum.photos/id/1031/800/600',
                    rating: 3.4,
                    reviews: 170,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '박물관',
                    create_at: '2024-05-06 00:00:00',
                    update_at: '2024-05-06 00:00:00',
                    detail: {},
                },
                {
                    id: 8,
                    title: '슬기샘도서관',
                    category: '도서관',
                    description: '조용하게 공부하기 좋은 도서관',
                    image: 'https://picsum.photos/id/1035/800/600',
                    rating: 0.6,
                    reviews: 30,
                    location: '수원시 장안구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '도서관',
                    create_at: '2024-05-01 00:00:00',
                    update_at: '2024-05-01 00:00:00',
                    detail: {},
                },
                {
                    id: 9,
                    title: '광교중앙도서관',
                    category: '도서관',
                    description: '뷰가 좋은 현대식 도서관',
                    image: 'https://picsum.photos/id/1039/800/600',
                    rating: 1.1,
                    reviews: 55,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '도서관',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
                {
                    id: 10,
                    title: '행리단길',
                    category: '지역명소',
                    description: '감성 카페와 맛집 거리',
                    image: 'https://picsum.photos/id/1043/800/600',
                    rating: 4.4,
                    reviews: 220,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-07 00:00:00',
                    update_at: '2024-05-07 00:00:00',
                    detail: {},
                },
                {
                    id: 11,
                    title: '팔달산',
                    category: '지역명소',
                    description: '수원을 한눈에 볼 수 있는 명산',
                    image: 'https://picsum.photos/id/1050/800/600',
                    rating: 2.8,
                    reviews: 140,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-03 00:00:00',
                    update_at: '2024-05-03 00:00:00',
                    detail: {},
                },
                {
                    id: 12,
                    title: '효원공원',
                    category: '공원',
                    description: '중국식 정원이 있는 공원',
                    image: 'https://picsum.photos/id/1060/800/600',
                    rating: 1.9,
                    reviews: 95,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
            ],
        }
    },

    // Food
    food: {
        "성남시" : {
            totalCount : 1,
            perPage : 12, 
            categories: ['전체', '한식', '중식', '일식', '양식'],
            items : [
                {
                    id: 1,
                    title: "수원 왕갈비탕",
                    category: "한식",
                    description: "60년 전통의 진한 사골육수로 우려낸 수원 대표 왕갈비탕. 두툼한 갈비살이 일품입니다.",
                    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
                    rating: 4.8,
                    reviews: 324,
                    location: "경기도 수원시 팔달구",
                    address: "경기도 수원시 팔달구 행궁로 45",
                    tag: "한식",
                    create_at: "2024-05-01 00:00:00",
                    update_at: "2024-05-01 00:00:00",
                    detail: {},
                },
                {
                    id: 2,
                    title: "화성 통닭골목",
                    category: "한식",
                    description: "수원 화성 인근 유명 통닭골목. 바삭한 튀김옷과 육즙 가득한 통닭이 유명합니다.",
                    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&q=80",
                    rating: 4.7,
                    reviews: 512,
                    location: "경기도 수원시 팔달구 정조로",
                    address: "경기도 수원시 팔달구 정조로 777",
                    tag: "한식",
                    create_at: "2024-05-02 00:00:00",
                    update_at: "2024-05-02 00:00:00",
                    detail: {},
                },
                {
                    id: 3,
                    title: "행궁동 스시 오마카세",
                    category: "일식",
                    description: "제철 해산물로 구성된 프리미엄 오마카세. 수원에서 즐기는 도심 속 미식 경험.",
                    image: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80",
                    rating: 4.9,
                    reviews: 198,
                    location: "경기도 수원시 팔달구 행궁로",
                    address: "경기도 수원시 팔달구 행궁로 12",
                    tag: "일식",
                    create_at: "2024-05-03 00:00:00",
                    update_at: "2024-05-03 00:00:00",
                    detail: {},
                },
                {
                    id: 4,
                    title: "수원 짜장면 원조",
                    category: "중식",
                    description: "50년 전통의 수타면 짜장면. 춘장의 깊은 맛과 쫄깃한 면발이 특징입니다.",
                    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
                    rating: 4.5,
                    reviews: 276,
                    location: "경기도 수원시 영통구 영통로",
                    address: "경기도 수원시 영통구 영통로 88",
                    tag: "중식",
                    create_at: "2024-05-04 00:00:00",
                    update_at: "2024-05-04 00:00:00",
                    detail: {},
                },
                {
                    id: 5,
                    title: "인계동 파스타",
                    category: "양식",
                    description: "이탈리아 정통 레시피로 만든 수제 파스타. 트러플 크림 파스타가 시그니처입니다.",
                    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
                    rating: 4.6,
                    reviews: 145,
                    location: "경기도 수원시 팔달구 인계로",
                    address: "경기도 수원시 팔달구 인계로 55",
                    tag: "양식",
                    create_at: "2024-05-05 00:00:00",
                    update_at: "2024-05-05 00:00:00",
                    detail: {},
                },
                {
                    id: 6,
                    title: "광교 육회비빔밥",
                    category: "한식",
                    description: "신선한 한우 육회와 참기름 향이 어우러진 정통 육회비빔밥. 광교 맛집 1위.",
                    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80",
                    rating: 4.7,
                    reviews: 389,
                    location: "경기도 수원시 영통구 광교로 145",
                    address: "경기도 수원시 영통구 광교로",
                    tag: "한식",
                    create_at: "2024-05-06 00:00:00",
                    update_at: "2024-05-06 00:00:00",
                    detail: {},
                },
                {
                    id: 7,
                    title: "매탄동 라멘집",
                    category: "일식",
                    description: "12시간 우린 돈코츠 육수의 진한 라멘. 일본 현지 감성 그대로 재현한 수원 맛집.",
                    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
                    rating: 4.4,
                    reviews: 231,
                    location: "경기도 수원시 영통구 매탄로",
                    address: "경기도 수원시 영통구 매탄로 33",
                    tag: "일식",
                    create_at: "2024-05-07 00:00:00",
                    update_at: "2024-05-07 00:00:00",
                    detail: {},
                },
                {
                    id: 8,
                    title: "팔달문 갈비찜",
                    category: "한식",
                    description: "간장 양념에 24시간 재운 특제 갈비찜. 부드러운 육질과 달콤한 양념이 일품.",
                    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
                    rating: 4.8,
                    reviews: 467,
                    location: "경기도 수원시 팔달구 팔달로",
                    address: "경기도 수원시 팔달구 팔달로 200",
                    tag: "한식",
                    create_at: "2024-05-08 00:00:00",
                    update_at: "2024-05-08 00:00:00",
                    detail: {},
                },
                {
                    id: 9,
                    title: "영통 스테이크하우스",
                    category: "양식",
                    description: "드라이에이징 한우 스테이크 전문점. 풍부한 마블링과 깊은 풍미가 특징.",
                    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
                    rating: 4.6,
                    reviews: 162,
                    location: "경기도 수원시 영통구 영통로",
                    address: "경기도 수원시 영통구 영통로 99",
                    tag: "양식",
                    create_at: "2024-05-09 00:00:00",
                    update_at: "2024-05-09 00:00:00",
                    detail: {},
                },
                {
                    id: 10,
                    title: "수원 순대국밥",
                    category: "한식",
                    description: "구수한 뼈 육수에 듬뿍 담긴 순대와 내장. 이른 아침부터 줄 서는 수원 명물 국밥집.",
                    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
                    rating: 4.5,
                    reviews: 310,
                    location: "경기도 수원시 권선구 권선로",
                    address: "경기도 수원시 권선구 권선로 123",
                    tag: "한식",
                    create_at: "2024-05-10 00:00:00",
                    update_at: "2024-05-10 00:00:00",
                    detail: {},
                },
                {
                    id: 11,
                    title: "광교 딤섬하우스",
                    category: "중식",
                    description: "홍콩식 정통 딤섬을 광교 신도시에서. 하가우·소룡포·차슈바오가 특히 인기.",
                    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80",
                    rating: 4.6,
                    reviews: 189,
                    location: "경기도 수원시 영통구 광교중앙로",
                    address: "경기도 수원시 영통구 광교중앙로 100",
                    tag: "중식",
                    create_at: "2024-05-11 00:00:00",
                    update_at: "2024-05-11 00:00:00",
                    detail: {},
                },
            ],
        }
    },

    sleep: {
        "성남시": {
            totalCount: 5,
            perPage: 12,
            categories: ['전체', '호텔', '리조트', '펜션', '게스트하우스'],
            items: [
            {
                id: 1,
                title: '수원 화성 한옥 게스트하우스',
                category: '게스트하우스',
                description:
                '수원 화성 인근에 위치한 전통 한옥 스타일 게스트하우스입니다. 고즈넉한 한옥의 멋을 느끼며 편안한 휴식을 즐길 수 있으며, 화성행궁까지 도보 5분 거리에 위치해 관광에 최적화된 숙소입니다.',

                image:
                'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',

                rating: 4.8,
                reviews: 124,

                location: '경기도 수원시 팔달구',
                address: '경기도 수원시 팔달구 행궁로 12-3',

                tag: '게스트하우스',

                create_at: '2024-05-01 00:00:00',
                update_at: '2024-05-01 00:00:00',

                // 확장 정보 (detail용)
                detail: {
                    lat: 37.2788,
                    lng: 127.0133,

                    checkIn: '15:00',
                    checkOut: '11:00',

                    price: '70,000원~/박',
                    phone: '031-111-1111',

                    facilities: ['무료 Wi-Fi', '주차 가능', '조식 포함', '에어컨'],

                    tags: ['한옥', '도보여행', '가족'],

                    reviews_list: [
                        { user: '여행자A', rating: 5, comment: '한옥 분위기가 너무 좋았어요!' },
                        { user: '여행자B', rating: 4, comment: '조용하고 깔끔했어요.' },
                        { user: '여행자C', rating: 5, comment: '사장님 친절 + 조식 최고' },
                    ],
                },
            },

            {
                id: 2,
                title: '수원 팰리스 호텔',
                category: '호텔',

                description:
                '광교신도시 중심부에 위치한 현대적인 호텔로 비즈니스와 관광 모두에 적합합니다.',

                image:
                'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',

                rating: 4.5,
                reviews: 98,

                location: '경기도 수원시 영통구',
                address: '경기도 수원시 영통구 광교중앙로 170',

                tag: '호텔',

                create_at: '2024-05-02 00:00:00',
                update_at: '2024-05-02 00:00:00',

                detail: {
                    lat: 37.2910,
                    lng: 127.0457,

                    checkIn: '14:00',
                    checkOut: '12:00',

                    price: '150,000원~/박',
                    phone: '031-111-2222',

                    facilities: ['Wi-Fi', '주차', '레스토랑', '피트니스', '수영장'],

                    tags: ['호텔', '비즈니스', '광교'],

                    reviews_list: [
                        { user: '여행자F', rating: 5, comment: '루프탑 뷰 최고!' },
                        { user: '여행자G', rating: 4, comment: '시설 깔끔' },
                    ],
                },
            },

            {
                id: 3,
                title: '수원 이비스 앰배서더',
                category: '호텔',

                description:
                '수원역 인근에 위치해 교통이 매우 편리한 호텔입니다.',

                image:
                'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80',

                rating: 4.3,
                reviews: 210,

                location: '경기도 수원시 권선구',
                address: '경기도 수원시 권선구 덕영대로 924',

                tag: '호텔',

                create_at: '2024-05-03 00:00:00',
                update_at: '2024-05-03 00:00:00',

                detail: {
                    lat: 37.2659,
                    lng: 127.0006,

                    checkIn: '15:00',
                    checkOut: '11:00',

                    price: '100,000원~/박',
                    phone: '031-111-3333',

                    facilities: ['Wi-Fi', '주차', '레스토랑', '바'],

                    tags: ['호텔', '수원역', '교통'],

                    reviews_list: [],
                },
            },

            {
                id: 4,
                title: '수원 광교 스테이',
                category: '펜션',

                description:
                '광교호수공원 바로 옆에 위치한 프리미엄 펜션입니다.',

                image:
                'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',

                rating: 4.6,
                reviews: 67,

                location: '경기도 수원시 영통구',
                address: '경기도 수원시 영통구 광교호수공원로 99',

                tag: '펜션',

                create_at: '2024-05-04 00:00:00',
                update_at: '2024-05-04 00:00:00',

                detail: {
                    lat: 37.2993,
                    lng: 127.0517,

                    checkIn: '16:00',
                    checkOut: '11:00',

                    price: '130,000원~/박',
                    phone: '031-111-4444',

                    facilities: ['Wi-Fi', '주차', '바베큐', '자전거'],

                    tags: ['펜션', '호수뷰', '자연'],

                    reviews_list: [],
                },
            },

            {
                id: 5,
                title: '수원 화성 게스트인',
                category: '게스트하우스',

                description:
                '배낭여행객과 솔로 여행자를 위한 아늑한 게스트하우스입니다.',

                image:
                'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',

                rating: 4.1,
                reviews: 43,

                location: '경기도 수원시 팔달구',
                address: '경기도 수원시 팔달구 정조로 870',

                tag: '게스트하우스',

                create_at: '2024-05-05 00:00:00',
                update_at: '2024-05-05 00:00:00',

                detail: {
                    lat: 37.2821,
                    lng: 127.0187,

                    checkIn: '15:00',
                    checkOut: '10:00',

                    price: '45,000원~/박',
                    phone: '031-111-5555',

                    facilities: ['Wi-Fi', '공용주방', '라운지'],

                    tags: ['가성비', '솔로여행'],

                    reviews_list: [],
                },
            },
            ]
        },
    },
    playf: {
        "성남시" : {
            totalCount : 1,
            perPage : 12, 
            categories: ['전체', '박물관', '도서관', '지역명소', '공원'],
            items : [
                {
                    id: 1,
                    title: '수원 화성',
                    category: '지역명소',
                    description: '조선 정조가 축성한 세계문화유산',
                    image: 'https://picsum.photos/id/1011/800/600',
                    rating: 4.5,
                    reviews: 120,
                    liked : true,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-01 12:00:00',
                    update_at: '2024-05-01 12:00:00',
                    detail: {},
                },
                {
                    id: 2,
                    title: '화성행궁',
                    category: '지역명소',
                    description: '정조가 머물던 임시 궁궐',
                    image: 'https://picsum.photos/id/1015/800/600',
                    rating: 3.5,
                    reviews: 98,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-01 12:00:00',
                    update_at: '2024-05-01 12:00:00',
                    detail: {},
                },
                {
                    id: 3,
                    title: '광교호수공원',
                    category: '공원',
                    description: '도심 속 힐링 호수 공원',
                    image: 'https://picsum.photos/id/1016/800/600',
                    rating: 3.2,
                    reviews: 208,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
                {
                    id: 4,
                    title: '만석공원',
                    category: '공원',
                    description: '조용한 힐링 공원',
                    image: 'https://picsum.photos/id/1020/800/600',
                    rating: 3.0,
                    reviews: 150,
                    location: '수원시 장안구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-04-29 00:00:00',
                    update_at: '2024-04-29 00:00:00',
                    detail: {},
                },
                {
                    id: 5,
                    title: '서호공원',
                    category: '공원',
                    description: '노을이 아름다운 호수 공원',
                    image: 'https://picsum.photos/id/1024/800/600',
                    rating: 1.6,
                    reviews: 80,
                    location: '수원시 권선구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-04-25 00:00:00',
                    update_at: '2024-04-25 00:00:00',
                    detail: {},
                },
                {
                    id: 6,
                    title: '수원박물관',
                    category: '박물관',
                    description: '수원의 역사와 문화를 한눈에',
                    image: 'https://picsum.photos/id/1027/800/600',
                    rating: 1.2,
                    reviews: 60,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '박물관',
                    create_at: '2024-05-04 00:00:00',
                    update_at: '2024-05-04 00:00:00',
                    detail: {},
                },
                {
                    id: 7,
                    title: '삼성이노베이션뮤지엄',
                    category: '박물관',
                    description: '삼성의 기술 발전을 볼 수 있는 공간',
                    image: 'https://picsum.photos/id/1031/800/600',
                    rating: 3.4,
                    reviews: 170,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '박물관',
                    create_at: '2024-05-06 00:00:00',
                    update_at: '2024-05-06 00:00:00',
                    detail: {},
                },
                {
                    id: 8,
                    title: '슬기샘도서관',
                    category: '도서관',
                    description: '조용하게 공부하기 좋은 도서관',
                    image: 'https://picsum.photos/id/1035/800/600',
                    rating: 0.6,
                    reviews: 30,
                    location: '수원시 장안구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '도서관',
                    create_at: '2024-05-01 00:00:00',
                    update_at: '2024-05-01 00:00:00',
                    detail: {},
                },
                {
                    id: 9,
                    title: '광교중앙도서관',
                    category: '도서관',
                    description: '뷰가 좋은 현대식 도서관',
                    image: 'https://picsum.photos/id/1039/800/600',
                    rating: 1.1,
                    reviews: 55,
                    location: '수원시 영통구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '도서관',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
                {
                    id: 10,
                    title: '행리단길',
                    category: '지역명소',
                    description: '감성 카페와 맛집 거리',
                    image: 'https://picsum.photos/id/1043/800/600',
                    rating: 4.4,
                    reviews: 220,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-07 00:00:00',
                    update_at: '2024-05-07 00:00:00',
                    detail: {},
                },
                {
                    id: 11,
                    title: '팔달산',
                    category: '지역명소',
                    description: '수원을 한눈에 볼 수 있는 명산',
                    image: 'https://picsum.photos/id/1050/800/600',
                    rating: 2.8,
                    reviews: 140,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '지역명소',
                    create_at: '2024-05-03 00:00:00',
                    update_at: '2024-05-03 00:00:00',
                    detail: {},
                },
                {
                    id: 12,
                    title: '효원공원',
                    category: '공원',
                    description: '중국식 정원이 있는 공원',
                    image: 'https://picsum.photos/id/1060/800/600',
                    rating: 1.9,
                    reviews: 95,
                    location: '수원시 팔달구',
                    address: '경기도 수원시 팔달구 창룡대로 103번길 20',
                    tag: '공원',
                    create_at: '2024-05-02 00:00:00',
                    update_at: '2024-05-02 00:00:00',
                    detail: {},
                },
            ],
        }
    },
};

export default TEMP_API_LIST_DATA;