export const lifePosts = [
  {
    id: 16,
    title: "서울 야경 명소 발견!",
    author: "서울시민",
    place: "서울 남산타워",
    regDt: "2026-04-29",
    viewCnt: 312,
    wishCnt: 45,
    commentCnt: 8,
    hashtags: ["야경", "서울", "핫플"],
    img: "https://picsum.photos/seed/life-16/720/920",
    description:
      "인생샷 남기기 좋은 서울 야경 명소예요. 밤공기 맞으면서 산책하기도 좋았습니다.",
    category: "볼거리",
    size: "tall",
  },
  {
    id: 15,
    title: "제주도 숨은 카페 공유해요",
    author: "여행가J",
    place: "제주 애월 카페거리",
    regDt: "2026-04-28",
    viewCnt: 521,
    wishCnt: 88,
    commentCnt: 14,
    hashtags: ["제주", "카페", "바다뷰"],
    img: "https://picsum.photos/seed/life-15/720/640",
    description:
      "창가 자리에서 인생샷 찍기 좋은 카페였어요. 바다뷰가 정말 예뻤습니다.",
    category: "먹거리",
    size: "wide",
  },
  {
    id: 14,
    title: "강릉 바다 힐링 여행",
    author: "파도사랑",
    place: "강릉 안목해변",
    regDt: "2026-04-27",
    viewCnt: 198,
    wishCnt: 23,
    commentCnt: 5,
    hashtags: ["강릉", "바다", "힐링"],
    img: "https://picsum.photos/seed/life-14/720/900",
    description:
      "바다를 배경으로 사진 찍기 좋은 여행 코스예요. 조용히 걷기에도 좋았습니다.",
    category: "볼거리",
    size: "tall",
  },
  {
    id: 13,
    title: "부산 밀면 맛집 인증",
    author: "미식가",
    place: "부산 서면",
    regDt: "2026-04-26",
    viewCnt: 742,
    wishCnt: 120,
    commentCnt: 21,
    hashtags: ["부산", "맛집", "밀면"],
    img: "https://picsum.photos/seed/life-13/720/720",
    description:
      "음식 사진도 예쁘게 나오는 부산 맛집이에요. 여행 중 먹거리 코스로 추천합니다.",
    category: "먹거리",
    size: "square",
  },
  {
    id: 12,
    title: "전주 한옥마을 산책",
    author: "한옥러버",
    place: "전주 한옥마을",
    regDt: "2026-04-25",
    viewCnt: 355,
    wishCnt: 56,
    commentCnt: 9,
    hashtags: ["전주", "한옥마을", "산책"],
    img: "https://picsum.photos/seed/life-12/720/860",
    description:
      "한복 입고 찍으면 분위기 좋은 인생샷 코스예요. 골목마다 볼거리가 많았습니다.",
    category: "놀거리",
    size: "tall",
  },
  {
    id: 11,
    title: "속초 중앙시장 먹거리 탐방",
    author: "먹방러",
    place: "속초 중앙시장",
    regDt: "2026-04-24",
    viewCnt: 410,
    wishCnt: 77,
    commentCnt: 11,
    hashtags: ["속초", "시장", "먹거리"],
    img: "https://picsum.photos/seed/life-11/720/620",
    description:
      "시장 분위기와 먹거리 사진을 남기기 좋아요. 간식 종류가 많아서 구경하는 재미도 있었습니다.",
    category: "먹거리",
    size: "wide",
  },
  {
    id: 10,
    title: "가을 단풍 구경 다녀옴",
    author: "단풍맨",
    place: "내장산 국립공원",
    regDt: "2026-04-23",
    viewCnt: 167,
    wishCnt: 34,
    commentCnt: 3,
    hashtags: ["단풍", "가을", "등산"],
    img: "https://picsum.photos/seed/life-10/720/930",
    description:
      "단풍 배경으로 사진 찍기 정말 좋았어요. 가을 여행 코스로 기억에 남는 곳입니다.",
    category: "볼거리",
    size: "tall",
  },
  {
    id: 9,
    title: "인천 월미도 나들이",
    author: "바다아이",
    place: "인천 월미도",
    regDt: "2026-04-22",
    viewCnt: 94,
    wishCnt: 12,
    commentCnt: 2,
    hashtags: ["인천", "월미도", "나들이"],
    img: "https://picsum.photos/seed/life-9/720/720",
    description:
      "놀이기구와 바다 배경이 잘 어울리는 곳이에요. 가볍게 다녀오기 좋았습니다.",
    category: "놀거리",
    size: "square",
  },
  {
    id: 8,
    title: "경기도 화성 1일차",
    author: "경기도 청년",
    place: "경기도 화성",
    regDt: "2026-04-21",
    viewCnt: 226,
    wishCnt: 30,
    commentCnt: 6,
    hashtags: ["경기도", "화성", "당일치기"],
    img: "https://picsum.photos/seed/life-8/720/840",
    description:
      "당일치기로 다녀오기 좋은 사진 코스였어요. 생각보다 볼거리가 많았습니다.",
    category: "볼거리",
    size: "tall",
  },
];

// 댓글 더미 데이터
export const lifeComments = [
  {
    id: 1,
    user: "여행초보",
    text: "사진 분위기 너무 좋아요!",
    date: "2026.04.22",
  },
  {
    id: 2,
    user: "감성러",
    text: "저도 여기 가보고 싶네요.",
    date: "2026.04.23",
  },
];

// 경기도 지역 목록
export const gyeonggiRegions = [
  "수원시", "용인시", "성남시", "부천시", "화성시", "안산시", "남양주시", "안양시", "평택시",
  "시흥시", "파주시", "의정부시", "김포시", "광명시", "광주시", "군포시", "이천시", "오산시",
  "하남시", "양주시", "구리시", "안성시", "포천시", "의왕시", "양평군", "여주시", "동두천시",
  "가평군", "과천시", "연천군",
];