// 잘거리(숙소) 더미 데이터 - 지역별 5개씩

const sleepDummyData = {
  수원시: [
    {
      id: 1,
      name: '수원 화성 한옥 게스트하우스',
      category: '게스트하우스',
      region: '수원시',
      rating: 4.8,
      reviewCount: 124,
      price: '70,000원~/박',
      address: '경기도 수원시 팔달구 행궁로 12-3',
      phone: '031-111-1111',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '수원 화성 인근에 위치한 전통 한옥 스타일 게스트하우스입니다. 고즈넉한 한옥의 멋을 느끼며 편안한 휴식을 즐길 수 있으며, 화성행궁까지 도보 5분 거리에 위치해 관광에 최적화된 숙소입니다. 조용한 골목길에 자리 잡아 도심 속 힐링을 원하는 여행객에게 인기가 높습니다.',
      tags: ['한옥', '도보여행', '가족'],
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
      lat: 37.2788, lng: 127.0133,
      facilities: ['무료 Wi-Fi', '주차 가능', '조식 포함', '에어컨'],
      reviews: [
        { user: '여행자A', rating: 5, comment: '한옥 분위기가 너무 좋았어요! 화성 관광하기 딱 좋은 위치입니다.' },
        { user: '여행자B', rating: 4, comment: '조용하고 깔끔해서 만족스러웠습니다.' },
        { user: '여행자C', rating: 5, comment: '사장님이 너무 친절하세요. 조식도 맛있었어요!' },
        { user: '여행자D', rating: 5, comment: '한옥에서 자는 경험이 정말 특별했어요. 꼭 다시 오고 싶습니다.' },
        { user: '여행자E', rating: 4, comment: '화성 바로 옆이라 걸어서 관광하기 편해요. 가성비도 좋아요.' },
      ],
    },
    {
      id: 2,
      name: '수원 팰리스 호텔',
      category: '호텔',
      region: '수원시',
      rating: 4.5,
      reviewCount: 98,
      price: '150,000원~/박',
      address: '경기도 수원시 영통구 광교중앙로 170',
      phone: '031-111-2222',
      checkIn: '14:00',
      checkOut: '12:00',
      description: '광교신도시 중심부에 위치한 현대적인 호텔로, 비즈니스와 관광 모두에 적합합니다. 넓고 쾌적한 객실과 함께 루프탑 레스토랑에서 광교 전경을 감상할 수 있습니다.',
      tags: ['호텔', '비즈니스', '광교'],
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      lat: 37.2910, lng: 127.0457,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '피트니스센터', '수영장'],
      reviews: [
        { user: '여행자F', rating: 5, comment: '루프탑 뷰가 정말 멋졌어요!' },
        { user: '여행자G', rating: 4, comment: '시설이 깔끔하고 직원분들이 친절해요.' },
        { user: '여행자H', rating: 5, comment: '수영장이 넓고 쾌적해서 아이들이 좋아했어요.' },
        { user: '여행자I', rating: 4, comment: '조식 뷔페가 다양하고 맛있었습니다.' },
        { user: '여행자J', rating: 4, comment: '광교 주변 쇼핑하기도 좋고 호텔 자체도 훌륭해요.' },
      ],
    },
    {
      id: 3,
      name: '수원 이비스 앰배서더',
      category: '호텔',
      region: '수원시',
      rating: 4.3,
      reviewCount: 210,
      price: '100,000원~/박',
      address: '경기도 수원시 권선구 덕영대로 924',
      phone: '031-111-3333',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '수원역 인근에 위치해 교통이 매우 편리한 호텔입니다. 합리적인 가격에 깔끔한 시설을 제공하며, 수원 시내 관광의 거점으로 활용하기에 좋습니다.',
      tags: ['호텔', '수원역', '편리한교통'],
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80',
      lat: 37.2659, lng: 127.0006,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '바'],
      reviews: [
        { user: '여행자K', rating: 4, comment: '수원역이랑 가깝고 가성비 최고예요.' },
        { user: '여행자L', rating: 5, comment: '직원분들이 정말 친절해요.' },
        { user: '여행자M', rating: 4, comment: '객실이 깔끔하고 편안했습니다.' },
        { user: '여행자N', rating: 3, comment: '위치는 좋은데 주차 공간이 좁은 게 아쉬웠어요.' },
        { user: '여행자O', rating: 5, comment: '가격 대비 퀄리티가 훌륭해요. 다음에도 이용할게요!' },
      ],
    },
    {
      id: 4,
      name: '수원 광교 스테이',
      category: '펜션',
      region: '수원시',
      rating: 4.6,
      reviewCount: 67,
      price: '130,000원~/박',
      address: '경기도 수원시 영통구 광교호수공원로 99',
      phone: '031-111-4444',
      checkIn: '16:00',
      checkOut: '11:00',
      description: '광교호수공원 바로 옆에 위치한 프리미엄 펜션입니다. 호수 전망의 객실에서 여유로운 시간을 보낼 수 있으며, 산책로와 자전거 대여도 즐길 수 있습니다.',
      tags: ['펜션', '호수뷰', '자연'],
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
      lat: 37.2993, lng: 127.0517,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '자전거 대여'],
      reviews: [
        { user: '여행자P', rating: 5, comment: '호수뷰가 너무 예뻐요. 힐링 그 자체!' },
        { user: '여행자Q', rating: 4, comment: '조용하고 깨끗해서 좋았습니다.' },
        { user: '여행자R', rating: 5, comment: '자전거 타고 호수 한 바퀴 돌았는데 너무 좋았어요.' },
        { user: '여행자S', rating: 5, comment: '바베큐 시설이 잘 갖춰져 있어서 가족들과 즐거운 시간 보냈어요.' },
        { user: '여행자T', rating: 4, comment: '호수 바로 앞이라 새벽 안개가 정말 예뻤습니다.' },
      ],
    },
    {
      id: 5,
      name: '수원 화성 게스트인',
      category: '게스트하우스',
      region: '수원시',
      rating: 4.1,
      reviewCount: 43,
      price: '45,000원~/박',
      address: '경기도 수원시 팔달구 정조로 870',
      phone: '031-111-5555',
      checkIn: '15:00',
      checkOut: '10:00',
      description: '배낭여행객과 솔로 여행자를 위한 아늑한 게스트하우스입니다. 저렴한 가격에 깨끗한 시설을 제공하며, 화성 관광지와 인접해 여행의 거점으로 제격입니다.',
      tags: ['게스트하우스', '가성비', '솔로여행'],
      image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
      lat: 37.2821, lng: 127.0187,
      facilities: ['무료 Wi-Fi', '공용 주방', '공용 라운지'],
      reviews: [
        { user: '여행자U', rating: 4, comment: '가성비 최고! 위치도 좋아요.' },
        { user: '여행자V', rating: 4, comment: '혼자 여행하기 딱 좋은 곳이에요.' },
        { user: '여행자W', rating: 3, comment: '공용 욕실이 조금 불편하지만 가격 생각하면 OK.' },
        { user: '여행자X', rating: 5, comment: '다른 여행자들과 교류할 수 있어서 즐거웠어요!' },
        { user: '여행자Y', rating: 4, comment: '화성 야경 보러 가기 딱 좋은 위치입니다.' },
      ],
    },
  ],

  성남시: [
    {
      id: 6,
      name: '판교 비즈니스 호텔',
      category: '호텔',
      region: '성남시',
      rating: 4.5,
      reviewCount: 89,
      price: '120,000원~/박',
      address: '경기도 성남시 분당구 판교역로 235',
      phone: '031-222-1111',
      checkIn: '14:00',
      checkOut: '12:00',
      description: '판교테크노밸리 인근에 위치한 깔끔한 비즈니스 호텔입니다. 출장객부터 여행객까지 누구에게나 편리한 입지를 자랑하며, 판교역에서 도보 3분 거리입니다.',
      tags: ['비즈니스', '출장', '판교'],
      image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80',
      lat: 37.3947, lng: 127.1112,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '회의실', '피트니스센터'],
      reviews: [
        { user: '출장러A', rating: 5, comment: '출장 때마다 이용해요. 시설이 최고입니다.' },
        { user: '여행자K', rating: 4, comment: '교통이 너무 편리해서 좋았습니다.' },
        { user: '출장러B', rating: 5, comment: '회의실 시설이 잘 갖춰져 있어요. 비즈니스 미팅하기 좋아요.' },
        { user: '여행자Z', rating: 4, comment: '판교역 바로 앞이라 이동이 편해요.' },
        { user: '출장러C', rating: 4, comment: '깔끔하고 조용해서 업무 보기 좋은 환경이에요.' },
      ],
    },
    {
      id: 7,
      name: '분당 라마다 호텔',
      category: '호텔',
      region: '성남시',
      rating: 4.4,
      reviewCount: 156,
      price: '140,000원~/박',
      address: '경기도 성남시 분당구 야탑로 278',
      phone: '031-222-2222',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '분당 야탑역 근처에 위치한 유명 체인 호텔입니다. 넓은 객실과 수준 높은 서비스로 많은 투숙객의 사랑을 받고 있으며, 주변에 쇼핑몰과 맛집이 즐비합니다.',
      tags: ['호텔', '분당', '쇼핑'],
      image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&q=80',
      lat: 37.4108, lng: 127.1265,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '바', '수영장', '스파'],
      reviews: [
        { user: '여행자L', rating: 5, comment: '서비스가 정말 훌륭해요!' },
        { user: '여행자M', rating: 4, comment: '객실이 넓고 쾌적합니다.' },
        { user: '여행자AA', rating: 5, comment: '스파 시설이 최고예요. 여행 피로가 싹 풀렸어요.' },
        { user: '여행자BB', rating: 4, comment: '수영장이 넓고 깨끗해서 좋았어요.' },
        { user: '여행자CC', rating: 4, comment: '주변에 맛집이 많아서 저녁 식사하기도 편해요.' },
      ],
    },
    {
      id: 8,
      name: '성남 모란 모텔',
      category: '모텔',
      region: '성남시',
      rating: 3.9,
      reviewCount: 34,
      price: '55,000원~/박',
      address: '경기도 성남시 중원구 모란로 45',
      phone: '031-222-3333',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '모란시장 인근의 깔끔한 모텔입니다. 합리적인 가격에 편안한 숙박을 제공하며, 모란 먹자골목을 도보로 이용할 수 있어 편리합니다.',
      tags: ['모텔', '가성비', '모란'],
      image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=600&q=80',
      lat: 37.4370, lng: 127.1244,
      facilities: ['무료 Wi-Fi', '주차 가능', '에어컨'],
      reviews: [
        { user: '여행자N', rating: 4, comment: '가격 대비 괜찮아요.' },
        { user: '여행자O', rating: 4, comment: '깨끗하고 직원이 친절합니다.' },
        { user: '여행자DD', rating: 3, comment: '모란시장 구경하기 좋은 위치예요.' },
        { user: '여행자EE', rating: 4, comment: '먹자골목 바로 앞이라 저녁 먹기 편해요.' },
        { user: '여행자FF', rating: 4, comment: '가성비 좋아요. 깔끔하게 하루 묵기 좋아요.' },
      ],
    },
    {
      id: 9,
      name: '판교 스마트 스테이',
      category: '게스트하우스',
      region: '성남시',
      rating: 4.2,
      reviewCount: 51,
      price: '65,000원~/박',
      address: '경기도 성남시 분당구 대왕판교로 660',
      phone: '031-222-4444',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '판교 IT밸리 인근의 스마트한 게스트하우스입니다. IT 종사자와 비즈니스 출장객을 위한 최적의 환경을 제공하며, 고속 인터넷과 업무 공간을 갖추고 있습니다.',
      tags: ['게스트하우스', 'IT', '비즈니스'],
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
      lat: 37.3967, lng: 127.1098,
      facilities: ['무료 Wi-Fi', '공용 업무공간', '카페', '주차 가능'],
      reviews: [
        { user: '여행자P', rating: 4, comment: '업무 환경이 잘 갖춰져 있어요.' },
        { user: '여행자Q', rating: 5, comment: '출장 때 딱이에요!' },
        { user: '여행자GG', rating: 4, comment: '인터넷 속도가 빠르고 공용 공간이 넓어요.' },
        { user: '여행자HH', rating: 4, comment: '카페에서 작업하기 좋아요.' },
        { user: '여행자II', rating: 3, comment: '가격이 조금 비싼 편이지만 시설은 좋아요.' },
      ],
    },
    {
      id: 10,
      name: '분당 아늑한 펜션',
      category: '펜션',
      region: '성남시',
      rating: 4.6,
      reviewCount: 72,
      price: '110,000원~/박',
      address: '경기도 성남시 분당구 불정로 90',
      phone: '031-222-5555',
      checkIn: '16:00',
      checkOut: '11:00',
      description: '탄천 변에 위치한 아늑한 펜션입니다. 자연 속에서 힐링할 수 있는 공간으로, 산책로와 자전거길이 바로 옆에 있어 액티비티를 즐기기에도 좋습니다.',
      tags: ['펜션', '자연', '힐링'],
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80',
      lat: 37.3803, lng: 127.1176,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '자전거 대여'],
      reviews: [
        { user: '여행자R', rating: 5, comment: '너무 예쁘고 조용해요!' },
        { user: '여행자S', rating: 4, comment: '바베큐가 즐거웠어요.' },
        { user: '여행자JJ', rating: 5, comment: '탄천 산책이 정말 좋았어요. 힐링 100%!' },
        { user: '여행자KK', rating: 4, comment: '자전거 대여해서 주변 돌아다니기 좋아요.' },
        { user: '여행자LL', rating: 5, comment: '인테리어가 예쁘고 아늑해요. 커플 여행 추천!' },
      ],
    },
  ],

  용인시: [
    {
      id: 11,
      name: '용인 에버랜드 리조트',
      category: '리조트',
      region: '용인시',
      rating: 4.9,
      reviewCount: 312,
      price: '250,000원~/박',
      address: '경기도 용인시 처인구 포곡읍 에버랜드로 199',
      phone: '031-333-1111',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '에버랜드 인근의 프리미엄 리조트입니다. 넓은 부지에 다양한 편의시설과 스파 시설을 갖추고 있으며, 에버랜드와 캐리비안베이를 도보로 이용할 수 있습니다.',
      tags: ['리조트', '에버랜드', '가족여행'],
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
      lat: 37.2930, lng: 127.2018,
      facilities: ['스파', '수영장', '레스토랑', '피트니스센터', '키즈클럽', '주차 가능'],
      reviews: [
        { user: '가족여행자A', rating: 5, comment: '아이들이 너무 좋아했어요!' },
        { user: '커플여행자A', rating: 5, comment: '스파가 최고였어요.' },
        { user: '가족여행자B', rating: 5, comment: '에버랜드 바로 옆이라 너무 편해요. 아이들 천국이에요.' },
        { user: '여행자MM', rating: 4, comment: '시설이 정말 훌륭해요. 키즈클럽이 특히 좋았어요.' },
        { user: '커플여행자B', rating: 5, comment: '수영장에서 하루 종일 놀다 왔어요. 최고의 리조트!' },
      ],
    },
    {
      id: 12,
      name: '기흥 레이크사이드 호텔',
      category: '호텔',
      region: '용인시',
      rating: 4.6,
      reviewCount: 178,
      price: '180,000원~/박',
      address: '경기도 용인시 기흥구 동백죽전대로 399',
      phone: '031-333-2222',
      checkIn: '15:00',
      checkOut: '12:00',
      description: '기흥 호수 옆에 위치한 아름다운 레이크사이드 호텔입니다. 호수 전망의 객실에서 여유로운 시간을 보낼 수 있으며, 주변 자연환경이 훌륭합니다.',
      tags: ['호텔', '호수뷰', '자연'],
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
      lat: 37.2804, lng: 127.1141,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '수영장', '스파'],
      reviews: [
        { user: '여행자NN', rating: 5, comment: '호수뷰가 정말 아름다워요!' },
        { user: '여행자OO', rating: 4, comment: '시설이 고급스럽고 깨끗해요.' },
        { user: '커플여행자C', rating: 5, comment: '창문 너머로 보이는 호수가 너무 예뻐요.' },
        { user: '여행자PP', rating: 4, comment: '레스토랑 음식도 맛있고 분위기 최고예요.' },
        { user: '여행자QQ', rating: 5, comment: '스파에서 피로를 싹 풀었어요. 재방문 의사 100%!' },
      ],
    },
    {
      id: 13,
      name: '용인 한옥 체험관',
      category: '게스트하우스',
      region: '용인시',
      rating: 4.4,
      reviewCount: 56,
      price: '80,000원~/박',
      address: '경기도 용인시 처인구 민속촌로 90',
      phone: '031-333-3333',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '한국민속촌 인근에 위치한 전통 한옥 체험관입니다. 조선시대 생활양식을 직접 체험할 수 있으며, 한복 대여 서비스도 제공합니다.',
      tags: ['한옥', '전통문화', '체험'],
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
      lat: 37.2398, lng: 127.1361,
      facilities: ['무료 Wi-Fi', '주차 가능', '한복 대여', '조식 포함'],
      reviews: [
        { user: '여행자RR', rating: 5, comment: '전통문화 체험이 인상 깊었어요!' },
        { user: '여행자SS', rating: 4, comment: '한복 입고 사진 찍기 좋아요.' },
        { user: '여행자TT', rating: 5, comment: '민속촌 입장권도 할인해줘서 좋았어요.' },
        { user: '여행자UU', rating: 4, comment: '조식이 맛있고 정갈해요. 전통 한식 맛봤어요.' },
        { user: '여행자VV', rating: 4, comment: '아이들 교육 여행으로 딱 좋은 곳이에요.' },
      ],
    },
    {
      id: 14,
      name: '수지 비즈니스 모텔',
      category: '모텔',
      region: '용인시',
      rating: 4.0,
      reviewCount: 29,
      price: '60,000원~/박',
      address: '경기도 용인시 수지구 풍덕천로 89',
      phone: '031-333-4444',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '수지구 중심에 위치한 깔끔한 모텔입니다. 편리한 교통과 합리적인 가격으로 비즈니스 출장객과 여행객 모두에게 적합합니다.',
      tags: ['모텔', '가성비', '수지'],
      image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=600&q=80',
      lat: 37.3212, lng: 127.0942,
      facilities: ['무료 Wi-Fi', '주차 가능', '에어컨'],
      reviews: [
        { user: '여행자WW', rating: 4, comment: '가격 대비 좋아요.' },
        { user: '여행자XX', rating: 4, comment: '깔끔하고 편안했습니다.' },
        { user: '여행자YY', rating: 3, comment: '무난해요. 하루 자고 가기엔 충분해요.' },
        { user: '여행자ZZ', rating: 4, comment: '직원분이 친절하고 체크인이 빠르게 됐어요.' },
        { user: '여행자AAA', rating: 5, comment: '수지 구경하기 좋은 위치예요. 깔끔해서 만족!' },
      ],
    },
    {
      id: 15,
      name: '양지 힐링 펜션',
      category: '펜션',
      region: '용인시',
      rating: 4.7,
      reviewCount: 93,
      price: '160,000원~/박',
      address: '경기도 용인시 처인구 양지면 양지리 100',
      phone: '031-333-5555',
      checkIn: '16:00',
      checkOut: '11:00',
      description: '양지 산자락에 위치한 프리미엄 힐링 펜션입니다. 숲속에서 자연을 만끽할 수 있으며, 독채 형태로 운영되어 프라이빗한 시간을 보낼 수 있습니다.',
      tags: ['펜션', '독채', '힐링', '숲속'],
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80',
      lat: 37.2306, lng: 127.3003,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '노천탕', '독채'],
      reviews: [
        { user: '커플여행자D', rating: 5, comment: '노천탕에서 별 보기 최고!' },
        { user: '가족여행자C', rating: 5, comment: '아이들과 바베큐 정말 즐거웠어요.' },
        { user: '여행자BBB', rating: 5, comment: '독채라 완전 프라이빗해요. 힐링 제대로 했어요.' },
        { user: '커플여행자E', rating: 4, comment: '숲 속 공기가 너무 상쾌해요. 다시 오고 싶어요.' },
        { user: '여행자CCC', rating: 5, comment: '노천탕이 정말 최고예요. 밤에 별 보면서 힐링 완료!' },
      ],
    },
  ],

  안양시: [
    {
      id: 16,
      name: '안양 평촌 호텔',
      category: '호텔',
      region: '안양시',
      rating: 4.3,
      reviewCount: 104,
      price: '110,000원~/박',
      address: '경기도 안양시 동안구 평촌대로 389',
      phone: '031-444-1111',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '평촌 신도시 중심에 위치한 호텔입니다. 깔끔한 시설과 친절한 서비스를 제공하며, 평촌 중앙공원과 가까워 산책하기 좋습니다.',
      tags: ['호텔', '평촌', '공원'],
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      lat: 37.3943, lng: 126.9528,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '피트니스센터'],
      reviews: [
        { user: '여행자DDD', rating: 4, comment: '평촌 구경하기 좋은 위치예요.' },
        { user: '여행자EEE', rating: 5, comment: '서비스가 정말 친절해요.' },
        { user: '여행자FFF', rating: 4, comment: '중앙공원 산책하기 좋아요.' },
        { user: '여행자GGG', rating: 4, comment: '깔끔하고 시설도 좋아요.' },
        { user: '여행자HHH', rating: 3, comment: '가격 대비 평범한 편이지만 위치가 좋아요.' },
      ],
    },
    {
      id: 17,
      name: '안양 아트센터 게스트하우스',
      category: '게스트하우스',
      region: '안양시',
      rating: 4.5,
      reviewCount: 62,
      price: '55,000원~/박',
      address: '경기도 안양시 만안구 안양로 189',
      phone: '031-444-2222',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '안양예술공원 인근에 위치한 아늑한 게스트하우스입니다. 예술적인 분위기와 자연이 어우러진 공간으로, 문화 여행객에게 인기가 높습니다.',
      tags: ['게스트하우스', '예술', '자연'],
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
      lat: 37.4060, lng: 126.9257,
      facilities: ['무료 Wi-Fi', '주차 가능', '공용 라운지', '조식 제공'],
      reviews: [
        { user: '여행자III', rating: 5, comment: '예술공원 산책하기 정말 좋아요!' },
        { user: '여행자JJJ', rating: 4, comment: '분위기가 너무 예뻐요.' },
        { user: '여행자KKK', rating: 5, comment: '조식이 맛있고 라운지가 아늑해요.' },
        { user: '여행자LLL', rating: 4, comment: '예술적인 인테리어가 마음에 들었어요.' },
        { user: '여행자MMM', rating: 4, comment: '가성비 좋고 직원분도 친절해요.' },
      ],
    },
    {
      id: 18,
      name: '안양 삼성산 펜션',
      category: '펜션',
      region: '안양시',
      rating: 4.6,
      reviewCount: 48,
      price: '120,000원~/박',
      address: '경기도 안양시 만안구 삼덕로 72',
      phone: '031-444-3333',
      checkIn: '16:00',
      checkOut: '11:00',
      description: '삼성산 자락에 위치한 자연 친화적 펜션입니다. 등산로 입구에 위치해 있어 등산객에게 특히 인기가 높으며, 신선한 공기와 아름다운 자연을 만끽할 수 있습니다.',
      tags: ['펜션', '등산', '자연'],
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80',
      lat: 37.3767, lng: 126.9138,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '등산 장비 대여'],
      reviews: [
        { user: '등산객A', rating: 5, comment: '등산 후 쉬기 딱이에요!' },
        { user: '여행자NNN', rating: 4, comment: '자연 속에서 힐링했어요.' },
        { user: '등산객B', rating: 5, comment: '등산 장비 대여 서비스가 정말 유용해요.' },
        { user: '여행자OOO', rating: 4, comment: '공기가 너무 맑고 좋아요. 바베큐도 즐거웠어요.' },
        { user: '등산객C', rating: 5, comment: '삼성산 등산하고 여기서 자는 조합이 최고예요.' },
      ],
    },
    {
      id: 19,
      name: '평촌 센트럴 모텔',
      category: '모텔',
      region: '안양시',
      rating: 3.8,
      reviewCount: 27,
      price: '50,000원~/박',
      address: '경기도 안양시 동안구 관양로 148',
      phone: '031-444-4444',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '평촌 중심가에 위치한 실속형 모텔입니다. 합리적인 가격과 깔끔한 객실로 가성비 숙박을 원하는 여행객에게 적합합니다.',
      tags: ['모텔', '가성비', '평촌'],
      image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=600&q=80',
      lat: 37.3954, lng: 126.9546,
      facilities: ['무료 Wi-Fi', '주차 가능'],
      reviews: [
        { user: '여행자PPP', rating: 4, comment: '가격 대비 만족합니다.' },
        { user: '여행자QQQ', rating: 3, comment: '깨끗하고 무난해요.' },
        { user: '여행자RRR', rating: 4, comment: '하루 자고 가기엔 충분해요.' },
        { user: '여행자SSS', rating: 3, comment: '위치는 좋지만 시설이 조금 노후화됐어요.' },
        { user: '여행자TTT', rating: 4, comment: '저렴하고 편리해요.' },
      ],
    },
    {
      id: 20,
      name: '안양 비즈니스 스테이',
      category: '게스트하우스',
      region: '안양시',
      rating: 4.2,
      reviewCount: 39,
      price: '65,000원~/박',
      address: '경기도 안양시 동안구 시민대로 230',
      phone: '031-444-5555',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '안양역 인근의 비즈니스 게스트하우스입니다. 출장객을 위한 업무 공간과 빠른 인터넷 환경을 제공하며, 교통이 매우 편리합니다.',
      tags: ['게스트하우스', '비즈니스', '안양역'],
      image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
      lat: 37.3940, lng: 126.9558,
      facilities: ['무료 Wi-Fi', '주차 가능', '공용 업무공간', '세탁기'],
      reviews: [
        { user: '출장러E', rating: 4, comment: '업무 공간이 잘 갖춰져 있어요.' },
        { user: '여행자UUU', rating: 4, comment: '역이랑 가까워서 편했어요.' },
        { user: '출장러F', rating: 5, comment: '인터넷 속도가 빠르고 조용해요.' },
        { user: '여행자VVV', rating: 3, comment: '시설은 좀 오래됐지만 위치가 좋아요.' },
        { user: '출장러G', rating: 4, comment: '출장 때 자주 이용해요. 가성비 좋아요.' },
      ],
    },
  ],

  안산시: [
    {
      id: 21,
      name: '안산 대부도 펜션',
      category: '펜션',
      region: '안산시',
      rating: 4.7,
      reviewCount: 134,
      price: '150,000원~/박',
      address: '경기도 안산시 단원구 대부황금로 1234',
      phone: '031-555-1111',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '서해 바다가 보이는 대부도의 프리미엄 펜션입니다. 낙조가 아름답기로 유명하며, 갯벌 체험과 낚시를 즐길 수 있습니다.',
      tags: ['펜션', '바다뷰', '낙조', '갯벌체험'],
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80',
      lat: 37.2178, lng: 126.5774,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '낚시대 대여', '조식 제공'],
      reviews: [
        { user: '여행자WWW', rating: 5, comment: '낙조가 너무 아름다워요!' },
        { user: '여행자XXX', rating: 5, comment: '갯벌체험이 즐거웠어요.' },
        { user: '가족여행자D', rating: 5, comment: '아이들이 갯벌 체험을 너무 좋아했어요.' },
        { user: '커플여행자F', rating: 4, comment: '낙조 보면서 바베큐하는 낭만이 최고예요.' },
        { user: '여행자YYY', rating: 5, comment: '낚시도 하고 신선한 해산물도 먹고 완벽한 여행이었어요.' },
      ],
    },
    {
      id: 22,
      name: '안산 그랜드 호텔',
      category: '호텔',
      region: '안산시',
      rating: 4.3,
      reviewCount: 87,
      price: '130,000원~/박',
      address: '경기도 안산시 단원구 화랑로 387',
      phone: '031-555-2222',
      checkIn: '14:00',
      checkOut: '12:00',
      description: '안산 중심가에 위치한 비즈니스 호텔입니다. 접근성이 뛰어나고 깔끔한 시설을 갖추고 있으며, 다양한 부대시설을 이용할 수 있습니다.',
      tags: ['호텔', '비즈니스', '안산'],
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      lat: 37.3219, lng: 126.8309,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '피트니스센터'],
      reviews: [
        { user: '여행자ZZZ', rating: 4, comment: '위치가 좋고 시설이 깔끔해요.' },
        { user: '여행자AAAA', rating: 5, comment: '직원분들이 친절해요.' },
        { user: '출장러H', rating: 4, comment: '출장 때 이용했는데 만족스러웠어요.' },
        { user: '여행자BBBB', rating: 4, comment: '레스토랑 음식이 맛있었어요.' },
        { user: '여행자CCCC', rating: 3, comment: '무난한 호텔이에요. 가격 대비 평범해요.' },
      ],
    },
    {
      id: 23,
      name: '시화호 뷰 게스트하우스',
      category: '게스트하우스',
      region: '안산시',
      rating: 4.1,
      reviewCount: 44,
      price: '50,000원~/박',
      address: '경기도 안산시 단원구 시화로 600',
      phone: '031-555-3333',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '시화호 인근에 위치한 아늑한 게스트하우스입니다. 철새 도래지와 인접해 있어 자연 관찰을 즐기는 여행객에게 인기가 있습니다.',
      tags: ['게스트하우스', '자연', '시화호'],
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
      lat: 37.3097, lng: 126.7312,
      facilities: ['무료 Wi-Fi', '주차 가능', '공용 라운지'],
      reviews: [
        { user: '여행자DDDD', rating: 4, comment: '시화호 뷰가 예뻐요.' },
        { user: '여행자EEEE', rating: 4, comment: '조용하고 편안했습니다.' },
        { user: '여행자FFFF', rating: 3, comment: '시설이 조금 오래됐지만 뷰는 최고예요.' },
        { user: '여행자GGGG', rating: 4, comment: '철새 구경하기 너무 좋은 위치예요.' },
        { user: '여행자HHHH', rating: 5, comment: '가성비 좋고 자연 환경이 너무 좋아요.' },
      ],
    },
    {
      id: 24,
      name: '안산 별빛 모텔',
      category: '모텔',
      region: '안산시',
      rating: 3.9,
      reviewCount: 31,
      price: '55,000원~/박',
      address: '경기도 안산시 상록구 사동로 120',
      phone: '031-555-4444',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '안산역 인근에 위치한 실속형 모텔입니다. 깔끔하고 편안한 객실을 합리적인 가격에 제공합니다.',
      tags: ['모텔', '가성비', '안산역'],
      image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=600&q=80',
      lat: 37.3196, lng: 126.8568,
      facilities: ['무료 Wi-Fi', '주차 가능', '에어컨'],
      reviews: [
        { user: '여행자IIII', rating: 4, comment: '가성비 좋아요.' },
        { user: '여행자JJJJ', rating: 4, comment: '깔끔하게 잘 관리되어 있어요.' },
        { user: '여행자KKKK', rating: 3, comment: '무난해요. 하루 자기엔 충분해요.' },
        { user: '여행자LLLL', rating: 4, comment: '안산역이랑 가까워서 편해요.' },
        { user: '여행자MMMM', rating: 4, comment: '저렴하고 깨끗해요.' },
      ],
    },
    {
      id: 25,
      name: '대부도 바다 리조트',
      category: '리조트',
      region: '안산시',
      rating: 4.8,
      reviewCount: 201,
      price: '220,000원~/박',
      address: '경기도 안산시 단원구 선감로 789',
      phone: '031-555-5555',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '서해 바다를 바라보며 즐기는 프리미엄 리조트입니다. 수영장과 스파, 레스토랑 등 다양한 부대시설을 갖추고 있으며, 아름다운 석양을 객실에서 감상할 수 있습니다.',
      tags: ['리조트', '바다뷰', '석양', '스파'],
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
      lat: 37.2389, lng: 126.5907,
      facilities: ['스파', '수영장', '레스토랑', '바', '피트니스센터', '주차 가능'],
      reviews: [
        { user: '커플여행자G', rating: 5, comment: '석양이 정말 환상적이에요!' },
        { user: '가족여행자E', rating: 5, comment: '아이들과 수영하기 최고!' },
        { user: '커플여행자H', rating: 5, comment: '바다 보면서 스파 즐기는 게 꿈만 같았어요.' },
        { user: '여행자NNNN', rating: 4, comment: '레스토랑 해산물 요리가 신선하고 맛있어요.' },
        { user: '가족여행자F', rating: 5, comment: '가족 모두 만족한 여행이었어요. 최고의 리조트!' },
      ],
    },
  ],

  고양시: [
    {
      id: 26,
      name: '일산 킨텍스 호텔',
      category: '호텔',
      region: '고양시',
      rating: 4.6,
      reviewCount: 223,
      price: '170,000원~/박',
      address: '경기도 고양시 일산서구 킨텍스로 217',
      phone: '031-666-1111',
      checkIn: '15:00',
      checkOut: '12:00',
      description: '킨텍스 전시장 인근에 위치한 대형 호텔입니다. 전시회, 박람회 참가자들에게 특히 인기가 높으며, 넓고 쾌적한 객실과 다양한 편의시설을 제공합니다.',
      tags: ['호텔', '킨텍스', '비즈니스'],
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80',
      lat: 37.6568, lng: 126.7598,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '바', '피트니스센터', '수영장'],
      reviews: [
        { user: '출장러I', rating: 5, comment: '킨텍스 바로 옆이라 너무 편했어요!' },
        { user: '여행자OOOO', rating: 4, comment: '시설이 훌륭해요.' },
        { user: '출장러J', rating: 5, comment: '박람회 참석 때마다 이용해요. 최고!' },
        { user: '여행자PPPP', rating: 4, comment: '수영장이 깨끗하고 넓어요.' },
        { user: '출장러K', rating: 4, comment: '피트니스 시설도 좋고 직원도 친절해요.' },
      ],
    },
    {
      id: 27,
      name: '고양 호수 펜션',
      category: '펜션',
      region: '고양시',
      rating: 4.7,
      reviewCount: 88,
      price: '140,000원~/박',
      address: '경기도 고양시 일산동구 호수로 595',
      phone: '031-666-2222',
      checkIn: '16:00',
      checkOut: '11:00',
      description: '일산 호수공원 인근의 아늑한 펜션입니다. 호수 주변의 아름다운 자연환경을 즐길 수 있으며, 산책로와 자전거도로가 잘 갖춰져 있습니다.',
      tags: ['펜션', '호수뷰', '자연', '자전거'],
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80',
      lat: 37.6685, lng: 126.7705,
      facilities: ['무료 Wi-Fi', '주차 가능', '바베큐', '자전거 대여'],
      reviews: [
        { user: '여행자QQQQ', rating: 5, comment: '호수공원 산책이 너무 좋았어요.' },
        { user: '여행자RRRR', rating: 4, comment: '조용하고 힐링이 됐어요.' },
        { user: '커플여행자I', rating: 5, comment: '호수 뷰 보며 커피 마시는 게 너무 좋았어요.' },
        { user: '가족여행자G', rating: 4, comment: '자전거 빌려서 호수 한 바퀴 돌았는데 최고였어요.' },
        { user: '여행자SSSS', rating: 5, comment: '바베큐 시설도 좋고 분위기가 너무 좋아요.' },
      ],
    },
    {
      id: 28,
      name: '대화역 비즈니스 게스트하우스',
      category: '게스트하우스',
      region: '고양시',
      rating: 4.2,
      reviewCount: 57,
      price: '60,000원~/박',
      address: '경기도 고양시 일산서구 대화동 2308',
      phone: '031-666-3333',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '대화역 도보 5분 거리의 비즈니스 게스트하우스입니다. 킨텍스 방문객과 출장객에게 최적화된 환경을 제공합니다.',
      tags: ['게스트하우스', '비즈니스', '킨텍스'],
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
      lat: 37.6598, lng: 126.7527,
      facilities: ['무료 Wi-Fi', '주차 가능', '공용 업무공간'],
      reviews: [
        { user: '출장러L', rating: 4, comment: '킨텍스 가기 편해요.' },
        { user: '여행자TTTT', rating: 4, comment: '가성비 좋아요.' },
        { user: '출장러M', rating: 5, comment: '업무 공간이 조용하고 집중하기 좋아요.' },
        { user: '여행자UUUU', rating: 3, comment: '시설이 조금 낡았지만 위치는 최고예요.' },
        { user: '출장러N', rating: 4, comment: '대화역 근처라 이동이 편해요.' },
      ],
    },
    {
      id: 29,
      name: '고양 아람 모텔',
      category: '모텔',
      region: '고양시',
      rating: 3.9,
      reviewCount: 22,
      price: '55,000원~/박',
      address: '경기도 고양시 덕양구 화중로 110',
      phone: '031-666-4444',
      checkIn: '15:00',
      checkOut: '11:00',
      description: '고양 시내 중심부에 위치한 깔끔한 모텔입니다. 합리적인 가격으로 편안한 숙박을 제공하며, 주변에 편의시설이 잘 갖춰져 있습니다.',
      tags: ['모텔', '가성비', '고양'],
      image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=600&q=80',
      lat: 37.6360, lng: 126.8317,
      facilities: ['무료 Wi-Fi', '주차 가능'],
      reviews: [
        { user: '여행자VVVV', rating: 4, comment: '무난하게 깨끗해요.' },
        { user: '여행자WWWW', rating: 4, comment: '가격이 저렴해서 좋아요.' },
        { user: '여행자XXXX', rating: 3, comment: '시설이 조금 오래됐어요.' },
        { user: '여행자YYYY', rating: 4, comment: '주변에 편의점이랑 식당이 많아요.' },
        { user: '여행자ZZZZ', rating: 4, comment: '하루 자기엔 충분해요. 깔끔해요.' },
      ],
    },
    {
      id: 30,
      name: '일산 프리미어 호텔',
      category: '호텔',
      region: '고양시',
      rating: 4.5,
      reviewCount: 169,
      price: '160,000원~/박',
      address: '경기도 고양시 일산동구 중앙로 1275',
      phone: '031-666-5555',
      checkIn: '14:00',
      checkOut: '12:00',
      description: '일산 중심가에 위치한 프리미엄 호텔입니다. 세련된 인테리어와 수준 높은 서비스를 제공하며, 다양한 쇼핑몰과 맛집이 인접해 있습니다.',
      tags: ['호텔', '쇼핑', '일산'],
      image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80',
      lat: 37.6583, lng: 126.7779,
      facilities: ['무료 Wi-Fi', '주차 가능', '레스토랑', '스파', '피트니스센터'],
      reviews: [
        { user: '여행자AAAAA', rating: 5, comment: '인테리어가 너무 세련됐어요.' },
        { user: '여행자BBBBB', rating: 4, comment: '서비스가 훌륭해요.' },
        { user: '여행자CCCCC', rating: 5, comment: '스파 시설이 최고예요. 완전 힐링!' },
        { user: '여행자DDDDD', rating: 4, comment: '주변 쇼핑몰이랑 가까워서 편해요.' },
        { user: '커플여행자J', rating: 5, comment: '분위기 좋고 서비스도 훌륭해요. 다시 오고 싶어요.' },
      ],
    },
  ],
};

// 지역명으로 숙소 데이터 조회
export const getSleepDataByRegion = (region) => {
  return sleepDummyData[region] || [];
};

// id로 숙소 단건 조회
export const getSleepDataById = (id) => {
  const allData = Object.values(sleepDummyData).flat();
  return allData.find((item) => item.id === Number(id)) || null;
};

// 연관 숙소 조회
export const getRelatedSleepData = (ids) => {
  const allData = Object.values(sleepDummyData).flat();
  return allData.filter((item) => ids.includes(item.id));
};

export default sleepDummyData;